accounts:
  - name: faucet
    coins: ["200000000exp"]
  - name: admin
    coins: ["200000000exp"]
validator:
  name: admin
  staked: "200000000exp"
client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: faucet
  coins: ["200000000exp"]
genesis:
  chain_id: "party-1"
  app_state:
    staking:
      params:
        bond_denom: "exp"
    mint:
      params:
        mint_denom: "exp"