// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gitgood/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// this line is used by starport scaffolding # 3
type QueryGetGoalRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetGoalRequest) Reset()         { *m = QueryGetGoalRequest{} }
func (m *QueryGetGoalRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetGoalRequest) ProtoMessage()    {}
func (*QueryGetGoalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c64abce84d2846e, []int{0}
}
func (m *QueryGetGoalRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetGoalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetGoalRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetGoalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetGoalRequest.Merge(m, src)
}
func (m *QueryGetGoalRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetGoalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetGoalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetGoalRequest proto.InternalMessageInfo

func (m *QueryGetGoalRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetGoalResponse struct {
	Goal *Goal `protobuf:"bytes,1,opt,name=Goal,proto3" json:"Goal,omitempty"`
}

func (m *QueryGetGoalResponse) Reset()         { *m = QueryGetGoalResponse{} }
func (m *QueryGetGoalResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetGoalResponse) ProtoMessage()    {}
func (*QueryGetGoalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c64abce84d2846e, []int{1}
}
func (m *QueryGetGoalResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetGoalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetGoalResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetGoalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetGoalResponse.Merge(m, src)
}
func (m *QueryGetGoalResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetGoalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetGoalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetGoalResponse proto.InternalMessageInfo

func (m *QueryGetGoalResponse) GetGoal() *Goal {
	if m != nil {
		return m.Goal
	}
	return nil
}

type QueryAllGoalRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllGoalRequest) Reset()         { *m = QueryAllGoalRequest{} }
func (m *QueryAllGoalRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllGoalRequest) ProtoMessage()    {}
func (*QueryAllGoalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c64abce84d2846e, []int{2}
}
func (m *QueryAllGoalRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllGoalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllGoalRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllGoalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllGoalRequest.Merge(m, src)
}
func (m *QueryAllGoalRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllGoalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllGoalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllGoalRequest proto.InternalMessageInfo

func (m *QueryAllGoalRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllGoalResponse struct {
	Goal       []*Goal             `protobuf:"bytes,1,rep,name=Goal,proto3" json:"Goal,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllGoalResponse) Reset()         { *m = QueryAllGoalResponse{} }
func (m *QueryAllGoalResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllGoalResponse) ProtoMessage()    {}
func (*QueryAllGoalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c64abce84d2846e, []int{3}
}
func (m *QueryAllGoalResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllGoalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllGoalResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllGoalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllGoalResponse.Merge(m, src)
}
func (m *QueryAllGoalResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllGoalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllGoalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllGoalResponse proto.InternalMessageInfo

func (m *QueryAllGoalResponse) GetGoal() []*Goal {
	if m != nil {
		return m.Goal
	}
	return nil
}

func (m *QueryAllGoalResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetStatRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetStatRequest) Reset()         { *m = QueryGetStatRequest{} }
func (m *QueryGetStatRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetStatRequest) ProtoMessage()    {}
func (*QueryGetStatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c64abce84d2846e, []int{4}
}
func (m *QueryGetStatRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetStatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetStatRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetStatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetStatRequest.Merge(m, src)
}
func (m *QueryGetStatRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetStatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetStatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetStatRequest proto.InternalMessageInfo

func (m *QueryGetStatRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetStatResponse struct {
	Stat *Stat `protobuf:"bytes,1,opt,name=Stat,proto3" json:"Stat,omitempty"`
}

func (m *QueryGetStatResponse) Reset()         { *m = QueryGetStatResponse{} }
func (m *QueryGetStatResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetStatResponse) ProtoMessage()    {}
func (*QueryGetStatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c64abce84d2846e, []int{5}
}
func (m *QueryGetStatResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetStatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetStatResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetStatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetStatResponse.Merge(m, src)
}
func (m *QueryGetStatResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetStatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetStatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetStatResponse proto.InternalMessageInfo

func (m *QueryGetStatResponse) GetStat() *Stat {
	if m != nil {
		return m.Stat
	}
	return nil
}

type QueryAllStatRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllStatRequest) Reset()         { *m = QueryAllStatRequest{} }
func (m *QueryAllStatRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllStatRequest) ProtoMessage()    {}
func (*QueryAllStatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c64abce84d2846e, []int{6}
}
func (m *QueryAllStatRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllStatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllStatRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllStatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllStatRequest.Merge(m, src)
}
func (m *QueryAllStatRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllStatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllStatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllStatRequest proto.InternalMessageInfo

func (m *QueryAllStatRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllStatResponse struct {
	Stat       []*Stat             `protobuf:"bytes,1,rep,name=Stat,proto3" json:"Stat,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllStatResponse) Reset()         { *m = QueryAllStatResponse{} }
func (m *QueryAllStatResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllStatResponse) ProtoMessage()    {}
func (*QueryAllStatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c64abce84d2846e, []int{7}
}
func (m *QueryAllStatResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllStatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllStatResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllStatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllStatResponse.Merge(m, src)
}
func (m *QueryAllStatResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllStatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllStatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllStatResponse proto.InternalMessageInfo

func (m *QueryAllStatResponse) GetStat() []*Stat {
	if m != nil {
		return m.Stat
	}
	return nil
}

func (m *QueryAllStatResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetTeamRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetTeamRequest) Reset()         { *m = QueryGetTeamRequest{} }
func (m *QueryGetTeamRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetTeamRequest) ProtoMessage()    {}
func (*QueryGetTeamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c64abce84d2846e, []int{8}
}
func (m *QueryGetTeamRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetTeamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetTeamRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetTeamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetTeamRequest.Merge(m, src)
}
func (m *QueryGetTeamRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetTeamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetTeamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetTeamRequest proto.InternalMessageInfo

func (m *QueryGetTeamRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetTeamResponse struct {
	Team *Team `protobuf:"bytes,1,opt,name=Team,proto3" json:"Team,omitempty"`
}

func (m *QueryGetTeamResponse) Reset()         { *m = QueryGetTeamResponse{} }
func (m *QueryGetTeamResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetTeamResponse) ProtoMessage()    {}
func (*QueryGetTeamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c64abce84d2846e, []int{9}
}
func (m *QueryGetTeamResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetTeamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetTeamResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetTeamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetTeamResponse.Merge(m, src)
}
func (m *QueryGetTeamResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetTeamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetTeamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetTeamResponse proto.InternalMessageInfo

func (m *QueryGetTeamResponse) GetTeam() *Team {
	if m != nil {
		return m.Team
	}
	return nil
}

type QueryAllTeamRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllTeamRequest) Reset()         { *m = QueryAllTeamRequest{} }
func (m *QueryAllTeamRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllTeamRequest) ProtoMessage()    {}
func (*QueryAllTeamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c64abce84d2846e, []int{10}
}
func (m *QueryAllTeamRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllTeamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllTeamRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllTeamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllTeamRequest.Merge(m, src)
}
func (m *QueryAllTeamRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllTeamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllTeamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllTeamRequest proto.InternalMessageInfo

func (m *QueryAllTeamRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllTeamResponse struct {
	Team       []*Team             `protobuf:"bytes,1,rep,name=Team,proto3" json:"Team,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllTeamResponse) Reset()         { *m = QueryAllTeamResponse{} }
func (m *QueryAllTeamResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllTeamResponse) ProtoMessage()    {}
func (*QueryAllTeamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c64abce84d2846e, []int{11}
}
func (m *QueryAllTeamResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllTeamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllTeamResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllTeamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllTeamResponse.Merge(m, src)
}
func (m *QueryAllTeamResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllTeamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllTeamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllTeamResponse proto.InternalMessageInfo

func (m *QueryAllTeamResponse) GetTeam() []*Team {
	if m != nil {
		return m.Team
	}
	return nil
}

func (m *QueryAllTeamResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetGoalRequest)(nil), "octalmage.gitgood.gitgood.QueryGetGoalRequest")
	proto.RegisterType((*QueryGetGoalResponse)(nil), "octalmage.gitgood.gitgood.QueryGetGoalResponse")
	proto.RegisterType((*QueryAllGoalRequest)(nil), "octalmage.gitgood.gitgood.QueryAllGoalRequest")
	proto.RegisterType((*QueryAllGoalResponse)(nil), "octalmage.gitgood.gitgood.QueryAllGoalResponse")
	proto.RegisterType((*QueryGetStatRequest)(nil), "octalmage.gitgood.gitgood.QueryGetStatRequest")
	proto.RegisterType((*QueryGetStatResponse)(nil), "octalmage.gitgood.gitgood.QueryGetStatResponse")
	proto.RegisterType((*QueryAllStatRequest)(nil), "octalmage.gitgood.gitgood.QueryAllStatRequest")
	proto.RegisterType((*QueryAllStatResponse)(nil), "octalmage.gitgood.gitgood.QueryAllStatResponse")
	proto.RegisterType((*QueryGetTeamRequest)(nil), "octalmage.gitgood.gitgood.QueryGetTeamRequest")
	proto.RegisterType((*QueryGetTeamResponse)(nil), "octalmage.gitgood.gitgood.QueryGetTeamResponse")
	proto.RegisterType((*QueryAllTeamRequest)(nil), "octalmage.gitgood.gitgood.QueryAllTeamRequest")
	proto.RegisterType((*QueryAllTeamResponse)(nil), "octalmage.gitgood.gitgood.QueryAllTeamResponse")
}

func init() { proto.RegisterFile("gitgood/query.proto", fileDescriptor_9c64abce84d2846e) }

var fileDescriptor_9c64abce84d2846e = []byte{
	// 540 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x96, 0x4f, 0x6f, 0xd3, 0x30,
	0x14, 0xc0, 0x9b, 0x76, 0x30, 0xc9, 0x48, 0x1c, 0x3c, 0x0e, 0x50, 0xa1, 0x0c, 0x22, 0xd8, 0x10,
	0x9a, 0x6c, 0x6d, 0xfb, 0x04, 0xe3, 0xb0, 0x1e, 0xb8, 0x40, 0xe1, 0x84, 0xc4, 0xc1, 0x6d, 0x2d,
	0x13, 0x29, 0x89, 0xb3, 0xd9, 0x45, 0x4c, 0x88, 0x0b, 0x9f, 0x00, 0x34, 0xf8, 0x4e, 0x1c, 0x27,
	0x71, 0xe1, 0x88, 0x5a, 0x3e, 0x08, 0xf2, 0x73, 0xd6, 0xb8, 0x61, 0xa5, 0xaf, 0xd2, 0x7a, 0x9a,
	0xec, 0xbd, 0x3f, 0xbf, 0xfc, 0x94, 0xf7, 0x52, 0xb2, 0xa5, 0x52, 0xab, 0xb4, 0x1e, 0xf1, 0x93,
	0xb1, 0x3c, 0x3d, 0x63, 0xe5, 0xa9, 0xb6, 0x9a, 0xde, 0xd3, 0x43, 0x2b, 0xb2, 0x5c, 0x28, 0xc9,
	0xaa, 0x7f, 0x5f, 0xfe, 0xed, 0xde, 0x57, 0x5a, 0xab, 0x4c, 0x72, 0x51, 0xa6, 0x5c, 0x14, 0x85,
	0xb6, 0xc2, 0xa6, 0xba, 0x30, 0x3e, 0xb1, 0xfb, 0x74, 0xa8, 0x4d, 0xae, 0x0d, 0x1f, 0x08, 0x23,
	0x7d, 0x45, 0xfe, 0x7e, 0x7f, 0x20, 0xad, 0xd8, 0xe7, 0xa5, 0x50, 0x69, 0x01, 0xc1, 0x55, 0x2c,
	0xbd, 0xec, 0xac, 0xb4, 0xc8, 0x9a, 0x77, 0xc6, 0x0a, 0xdb, 0xbc, 0xb3, 0x52, 0xe4, 0xfe, 0x2e,
	0x79, 0x4c, 0xb6, 0x5e, 0xba, 0xea, 0x3d, 0x69, 0x7b, 0x5a, 0x64, 0x7d, 0x79, 0x32, 0x96, 0xc6,
	0xd2, 0xdb, 0xa4, 0x9d, 0x8e, 0xee, 0x46, 0x0f, 0xa2, 0x27, 0x1b, 0xfd, 0x76, 0x3a, 0x4a, 0x9e,
	0x93, 0x3b, 0xf3, 0x61, 0xa6, 0xd4, 0x85, 0x91, 0xf4, 0x90, 0x6c, 0xb8, 0x33, 0x44, 0xde, 0x3a,
	0xd8, 0x66, 0x0b, 0x1f, 0x97, 0x41, 0x1a, 0x04, 0x27, 0x6f, 0xab, 0x9e, 0x47, 0x59, 0x16, 0xf6,
	0x3c, 0x26, 0xa4, 0x7e, 0xb4, 0xaa, 0xe2, 0x0e, 0xf3, 0x1e, 0x98, 0xf3, 0xc0, 0xbc, 0xd9, 0xca,
	0x03, 0x7b, 0x21, 0x94, 0xac, 0x72, 0xfb, 0x41, 0x66, 0xf2, 0x2d, 0xaa, 0x60, 0x67, 0xf5, 0xff,
	0x81, 0xed, 0xa0, 0x61, 0x69, 0x6f, 0x8e, 0xaa, 0x0d, 0x54, 0xbb, 0x4b, 0xa9, 0x7c, 0xc7, 0x39,
	0xac, 0xc0, 0xf4, 0x2b, 0x2b, 0x2c, 0xc2, 0xb4, 0x0f, 0xab, 0xe1, 0xdd, 0x19, 0x61, 0x1a, 0xd2,
	0x20, 0x38, 0x34, 0x1d, 0xf6, 0x5c, 0x87, 0xe9, 0x05, 0xb0, 0x1d, 0x34, 0xec, 0x5a, 0x4c, 0xbf,
	0x96, 0x22, 0x47, 0x98, 0xf6, 0x61, 0x35, 0xbc, 0x3b, 0x23, 0x4c, 0x43, 0x1a, 0x04, 0x87, 0xa6,
	0xc3, 0x9e, 0xeb, 0x30, 0xbd, 0x00, 0xb6, 0x83, 0x86, 0xbd, 0x36, 0xd3, 0x07, 0x5f, 0x37, 0xc9,
	0x0d, 0xc0, 0xa2, 0xdf, 0x23, 0x3f, 0x5c, 0x94, 0xfd, 0x07, 0xe1, 0x8a, 0x4d, 0xd3, 0xe5, 0xe8,
	0x78, 0xdf, 0x3f, 0xd9, 0xfb, 0xfc, 0xf3, 0xcf, 0x79, 0x7b, 0x87, 0x3e, 0xe2, 0xb3, 0x44, 0x3e,
	0x5b, 0x80, 0xc1, 0x22, 0xe4, 0x1f, 0xd3, 0xd1, 0x27, 0x7a, 0x1e, 0x91, 0x4d, 0x97, 0x7e, 0x94,
	0x21, 0xd0, 0xe6, 0x17, 0xd2, 0x72, 0xb4, 0xc6, 0x82, 0x49, 0x76, 0x01, 0xed, 0x21, 0xdd, 0x5e,
	0x82, 0x06, 0xb6, 0xe0, 0x9d, 0xc7, 0xd8, 0x0a, 0x26, 0x17, 0x65, 0x2b, 0x9c, 0x44, 0x94, 0x2d,
	0xf7, 0x89, 0xa8, 0x6d, 0xb9, 0x74, 0xac, 0xad, 0x95, 0xd0, 0x1a, 0x4b, 0x02, 0x65, 0xcb, 0xa1,
	0x81, 0x2d, 0x78, 0x6f, 0x31, 0xb6, 0x82, 0xe9, 0x43, 0xd9, 0x0a, 0xa7, 0x09, 0x65, 0xcb, 0x7d,
	0x3c, 0x6b, 0x5b, 0x2e, 0x1d, 0x6b, 0x6b, 0x25, 0xb4, 0xc6, 0xa0, 0xa3, 0x6c, 0x39, 0xb4, 0x67,
	0xc7, 0x3f, 0x26, 0x71, 0x74, 0x31, 0x89, 0xa3, 0xdf, 0x93, 0x38, 0xfa, 0x32, 0x8d, 0x5b, 0x17,
	0xd3, 0xb8, 0xf5, 0x6b, 0x1a, 0xb7, 0xde, 0xec, 0xa9, 0xd4, 0xbe, 0x1b, 0x0f, 0xd8, 0x50, 0xe7,
	0x57, 0x14, 0xf9, 0x50, 0x97, 0x39, 0x2b, 0xa5, 0x19, 0xdc, 0x84, 0x1f, 0x08, 0x87, 0x7f, 0x03,
	0x00, 0x00, 0xff, 0xff, 0x28, 0xb7, 0xf9, 0xbd, 0xd8, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries a goal by id.
	Goal(ctx context.Context, in *QueryGetGoalRequest, opts ...grpc.CallOption) (*QueryGetGoalResponse, error)
	// Queries a list of goal items.
	GoalAll(ctx context.Context, in *QueryAllGoalRequest, opts ...grpc.CallOption) (*QueryAllGoalResponse, error)
	// Queries a stat by id.
	Stat(ctx context.Context, in *QueryGetStatRequest, opts ...grpc.CallOption) (*QueryGetStatResponse, error)
	// Queries a list of stat items.
	StatAll(ctx context.Context, in *QueryAllStatRequest, opts ...grpc.CallOption) (*QueryAllStatResponse, error)
	// Queries a team by id.
	Team(ctx context.Context, in *QueryGetTeamRequest, opts ...grpc.CallOption) (*QueryGetTeamResponse, error)
	// Queries a list of team items.
	TeamAll(ctx context.Context, in *QueryAllTeamRequest, opts ...grpc.CallOption) (*QueryAllTeamResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Goal(ctx context.Context, in *QueryGetGoalRequest, opts ...grpc.CallOption) (*QueryGetGoalResponse, error) {
	out := new(QueryGetGoalResponse)
	err := c.cc.Invoke(ctx, "/octalmage.gitgood.gitgood.Query/Goal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GoalAll(ctx context.Context, in *QueryAllGoalRequest, opts ...grpc.CallOption) (*QueryAllGoalResponse, error) {
	out := new(QueryAllGoalResponse)
	err := c.cc.Invoke(ctx, "/octalmage.gitgood.gitgood.Query/GoalAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Stat(ctx context.Context, in *QueryGetStatRequest, opts ...grpc.CallOption) (*QueryGetStatResponse, error) {
	out := new(QueryGetStatResponse)
	err := c.cc.Invoke(ctx, "/octalmage.gitgood.gitgood.Query/Stat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) StatAll(ctx context.Context, in *QueryAllStatRequest, opts ...grpc.CallOption) (*QueryAllStatResponse, error) {
	out := new(QueryAllStatResponse)
	err := c.cc.Invoke(ctx, "/octalmage.gitgood.gitgood.Query/StatAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Team(ctx context.Context, in *QueryGetTeamRequest, opts ...grpc.CallOption) (*QueryGetTeamResponse, error) {
	out := new(QueryGetTeamResponse)
	err := c.cc.Invoke(ctx, "/octalmage.gitgood.gitgood.Query/Team", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TeamAll(ctx context.Context, in *QueryAllTeamRequest, opts ...grpc.CallOption) (*QueryAllTeamResponse, error) {
	out := new(QueryAllTeamResponse)
	err := c.cc.Invoke(ctx, "/octalmage.gitgood.gitgood.Query/TeamAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries a goal by id.
	Goal(context.Context, *QueryGetGoalRequest) (*QueryGetGoalResponse, error)
	// Queries a list of goal items.
	GoalAll(context.Context, *QueryAllGoalRequest) (*QueryAllGoalResponse, error)
	// Queries a stat by id.
	Stat(context.Context, *QueryGetStatRequest) (*QueryGetStatResponse, error)
	// Queries a list of stat items.
	StatAll(context.Context, *QueryAllStatRequest) (*QueryAllStatResponse, error)
	// Queries a team by id.
	Team(context.Context, *QueryGetTeamRequest) (*QueryGetTeamResponse, error)
	// Queries a list of team items.
	TeamAll(context.Context, *QueryAllTeamRequest) (*QueryAllTeamResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Goal(ctx context.Context, req *QueryGetGoalRequest) (*QueryGetGoalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Goal not implemented")
}
func (*UnimplementedQueryServer) GoalAll(ctx context.Context, req *QueryAllGoalRequest) (*QueryAllGoalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GoalAll not implemented")
}
func (*UnimplementedQueryServer) Stat(ctx context.Context, req *QueryGetStatRequest) (*QueryGetStatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stat not implemented")
}
func (*UnimplementedQueryServer) StatAll(ctx context.Context, req *QueryAllStatRequest) (*QueryAllStatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StatAll not implemented")
}
func (*UnimplementedQueryServer) Team(ctx context.Context, req *QueryGetTeamRequest) (*QueryGetTeamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Team not implemented")
}
func (*UnimplementedQueryServer) TeamAll(ctx context.Context, req *QueryAllTeamRequest) (*QueryAllTeamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TeamAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Goal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetGoalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Goal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/octalmage.gitgood.gitgood.Query/Goal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Goal(ctx, req.(*QueryGetGoalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GoalAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllGoalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GoalAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/octalmage.gitgood.gitgood.Query/GoalAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GoalAll(ctx, req.(*QueryAllGoalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetStatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/octalmage.gitgood.gitgood.Query/Stat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Stat(ctx, req.(*QueryGetStatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_StatAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllStatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).StatAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/octalmage.gitgood.gitgood.Query/StatAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).StatAll(ctx, req.(*QueryAllStatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Team_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Team(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/octalmage.gitgood.gitgood.Query/Team",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Team(ctx, req.(*QueryGetTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TeamAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TeamAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/octalmage.gitgood.gitgood.Query/TeamAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TeamAll(ctx, req.(*QueryAllTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "octalmage.gitgood.gitgood.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Goal",
			Handler:    _Query_Goal_Handler,
		},
		{
			MethodName: "GoalAll",
			Handler:    _Query_GoalAll_Handler,
		},
		{
			MethodName: "Stat",
			Handler:    _Query_Stat_Handler,
		},
		{
			MethodName: "StatAll",
			Handler:    _Query_StatAll_Handler,
		},
		{
			MethodName: "Team",
			Handler:    _Query_Team_Handler,
		},
		{
			MethodName: "TeamAll",
			Handler:    _Query_TeamAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gitgood/query.proto",
}

func (m *QueryGetGoalRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetGoalRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetGoalRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetGoalResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetGoalResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetGoalResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Goal != nil {
		{
			size, err := m.Goal.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllGoalRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllGoalRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllGoalRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllGoalResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllGoalResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllGoalResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Goal) > 0 {
		for iNdEx := len(m.Goal) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Goal[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetStatRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetStatRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetStatRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetStatResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetStatResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetStatResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Stat != nil {
		{
			size, err := m.Stat.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllStatRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllStatRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllStatRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllStatResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllStatResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllStatResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Stat) > 0 {
		for iNdEx := len(m.Stat) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Stat[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetTeamRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetTeamRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetTeamRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetTeamResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetTeamResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetTeamResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Team != nil {
		{
			size, err := m.Team.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllTeamRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllTeamRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllTeamRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllTeamResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllTeamResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllTeamResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Team) > 0 {
		for iNdEx := len(m.Team) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Team[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetGoalRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetGoalResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Goal != nil {
		l = m.Goal.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllGoalRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllGoalResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Goal) > 0 {
		for _, e := range m.Goal {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetStatRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetStatResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Stat != nil {
		l = m.Stat.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllStatRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllStatResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Stat) > 0 {
		for _, e := range m.Stat {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetTeamRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetTeamResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Team != nil {
		l = m.Team.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllTeamRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllTeamResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Team) > 0 {
		for _, e := range m.Team {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetGoalRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetGoalRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetGoalRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetGoalResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetGoalResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetGoalResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Goal", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Goal == nil {
				m.Goal = &Goal{}
			}
			if err := m.Goal.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllGoalRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllGoalRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllGoalRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllGoalResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllGoalResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllGoalResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Goal", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Goal = append(m.Goal, &Goal{})
			if err := m.Goal[len(m.Goal)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetStatRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetStatRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetStatRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetStatResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetStatResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetStatResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stat", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Stat == nil {
				m.Stat = &Stat{}
			}
			if err := m.Stat.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllStatRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllStatRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllStatRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllStatResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllStatResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllStatResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stat", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Stat = append(m.Stat, &Stat{})
			if err := m.Stat[len(m.Stat)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetTeamRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetTeamRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetTeamRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetTeamResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetTeamResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetTeamResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Team", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Team == nil {
				m.Team = &Team{}
			}
			if err := m.Team.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllTeamRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllTeamRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllTeamRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllTeamResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllTeamResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllTeamResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Team", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Team = append(m.Team, &Team{})
			if err := m.Team[len(m.Team)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
